version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data" # chmod 777 ./docker/dynamodb
    working_dir: /home/dynamodblocal
  processpdf:
    depends_on:
      - dynamodb-local
    build: .
    ports:
     - "9000:8080"
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_DEFAULT_REGION: 'us-east-1'
      DEV_LOCAL: "true"